<h1> TUTORIAL FOUR: </h1>
<h1> NON TESSREDUCE DATA </h1>
<h3> Author: Lindsey Gordon. Last Update: 11-27-22 </h3>
        
Load in data from another source (aka, how to spoof some input values)

This example uses data from TESS extracted via the **lygos** pipeline, which isn't published so we couldn't use it for the paper. Because it's TESS data, we do have sector, camera, and ccd data for this. If you don't have that, you should just use 0's -> I do this below to show how it should be formatted (yes, it uses strings, because usually you're ripping that info from a filename)

In [2]:
import numpy as np
from etsfit import etsMAIN
import etsfit.utils.utilities as ut
import pandas as pd
from astropy.time import Time

In [12]:
lygos_file = "./tutorial_data/rflxtarg_SN2018hzh_0431_30mn_n005_d4.0_of11.csv"
lygos_data = pd.read_csv(lygos_file)

time = np.asarray(lygos_data["# time [BJD]"])
flux = np.asarray(lygos_data[" relative flux"])
error = np.asarray(lygos_data[" relative flux error"])
targetlabel = "2018hzh"
sector = "00"
camera = "0"
ccd = "0"


TNSFile = "./tutorial_data/hzhtld_TNS.csv"
folder = "./tutorial_data/"

discoverytime = ut.get_disctime(TNSFile, targetlabel)

In [15]:
ets = etsMAIN(folder, TNSFile)
ets.load_single_lc(time, flux, error, discoverytime, 
                   targetlabel, sector, camera, ccd)
filterMade = ets.window_rms_filt(plot=False)
ets.pre_run_clean(1, cutIndices=filterMade, 
                    binning = False, fraction = None)
ets.run_MCMC(n1=10000, n2=30000, filesavetag="-lygos-single-power")

saving into folder:  ./tutorial_data/2018hzh0000/lygos-single-power/
 *** 
 *** 
 *** 
 ***
Beginning MCMC run
Starting burnin chain


 16%|█████▊                               | 4700/30000 [00:41<03:41, 114.02it/s]

Converged, ending chain


32900 samples post second run
$t_0$ 13.131163068948997 -0.06427432786198928 0.059811216112500176
A 0.09862538343267047 -0.0022890263662649624 0.002261775035380359
$\beta$ 0.5350006840415895 -0.00886799544807082 0.009141248559542126
b -0.1304890379309446 -0.0007018956994781778 0.0006935412264686691
log prob: [2693.51703334]
BAYESIAN INF CRIT:  [5414.48509834]


(array([[13.13116307,  0.09862538,  0.53500068, -0.13048904]]),
 array([[0.05981122, 0.00226178, 0.00914125, 0.00069354]]),
 array([[0.06427433, 0.00228903, 0.008868  , 0.0007019 ]]),
 5414.48509833604)